# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendations.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'recommendations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\x12\x0frecommendations\">\n\x15RecommendationRequest\x12\x11\n\tstrengths\x18\x01 \x01(\t\x12\x12\n\nweaknesses\x18\x02 \x01(\t\"1\n\x16RecommendationResponse\x12\x17\n\x0frecommendations\x18\x01 \x01(\t2\x80\x01\n\x15RecommendationService\x12g\n\x12GetRecommendations\x12&.recommendations.RecommendationRequest\x1a\'.recommendations.RecommendationResponse\"\x00\x42\x10Z\x0egrpc-go/protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016grpc-go/protos'
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=42
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=104
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=106
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=155
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=158
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
